### PR TITLE
Added ES Log, MSSQL Db Support and Redis Cache Functionality

### PR DESCRIPTION
**Pull request by TekyaygilFethi**
Last 10 messages can be fetch from db and be shown on screen on first connection of angular client. Each message and response will be recorded to db. But only last 10 will be fetched

### CODE REVIEW

**Comment by parisxmas** [comment]
Great job!

However, there are a few issues:

The response from the ChatGPT API is asynchronous, so response messages should be concatenated into one message for each user request instead of being sent separately.
The first and last messages from ChatGPT are null, and your SQL Message.Text field is not nullable. You can track the entire answer with these null values.

**Comment by parisxmas** [comment]
Great job!

However, there are a few issues:

The response from the ChatGPT API is asynchronous, so response messages should be concatenated into one message for each user request instead of being writing to SQL Message table separately.
The first and last messages from ChatGPT are null, and your SQL Message.Text field is not nullable. You can track the entire answer with these null values.

**Comment by TekyaygilFethi** [comment]
Hello,

Thank you! I don't have an Open API key (actually I have but exceeded quota :) ) That's why couldn't test the case the ChatGPT sends the real response. But I got your point, I think you are saying just like the chat gpt website, the response is coming in chunks. I will investigate it. Are there any events for finished chatgpt messages?

I thought the messages of ChatGPT shouldn't be null, Am I wrong? If so I will change my code to accept null values for text.

**Comment by parisxmas** [comment]
> 

As I can see, the first and last messages coming from the API are null. By detecting these packets, I can determine the start and end points for activating the client's blink cursor.

Please connect with me so I can provide you with an API key for development purposes

**Comment by TekyaygilFethi** [comment]
I will investigate the cursor event. Thank you for the trace. I am sending an e-mail about the API Key rn.

**Comment by TekyaygilFethi** [comment]
I've solved the problem of db inserts and inserting the chatgpt message as soon as it's finished

**Pull request merged**
